# Generated by Django 2.2.9 on 2020-02-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200205_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('internal', 'internal'), ('public', 'public')], default='internal', max_length=100),
        ),
    ]
