# Generated by Django 2.2.9 on 2020-10-23 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='author',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='script',
            name='file_created',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='file_updated',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='script',
            name='maintainer',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='script',
            name='status',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='script',
            name='tag',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='script',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
