# Generated by Django 2.2.9 on 2021-05-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20201023_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testsuite',
            name='script',
            field=models.ManyToManyField(to='projects.Script'),
        ),
    ]
