# Generated by Django 2.2.9 on 2021-05-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20210518_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='testsuite',
            name='suite_type',
            field=models.CharField(choices=[('Debug', 'Debug'), ('BVT', 'BVT'), ('Regression', 'Regression')], default='Debug', max_length=100),
        ),
    ]
