# Generated by Django 2.2.9 on 2021-06-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_testround'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testround',
            name='extra_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
